
pipeline:
  name: nodejs
  identifiers: # unused
  - package.json
  buildConfigs:
    imagestream: s2i-nodejs:8.10.0
    env:
    - name: npm_config_registry
      value: ${npm_config_registry}
    - name: npm_config_disturl
      value: https://npm.taobao.org/dist/
    - name: npm_config_phantomjs_cdnurl
      value: https://npm.taobao.org/dist/phantomjs/
    - name: npm_config_phantomjs_cdnurl
      value: https://npm.taobao.org/dist/phantomjs/
    - name: npm_config_electron_mirror
      value: https://npm.taobao.org/mirrors/electron/
    - name: npm_config_sass_binary_site
      value: https://npm.taobao.org/mirrors/node-sass/
    - name: BUILD_SCRIPT
      value: |
        echo === npm_config_registry: ${npm_config_registry} ===
        npm install --dev
        if [[ $? == 0 ]]; then
          echo "Build Successful."
        else
          echo "Build Failed!"
          exit 1
        fi

  deploymentConfigs:
    env:
    - name: NODE_ENV
      value: ${profile}
    - name: HOST
      value: 0.0.0.0
    - name: PORT
      value: 8080
    - name: project
      value: ${project}
    - name: RUN_SCRIPT
      value: |
        npm run build:${profile}
        if [[ $? == 0 ]]; then
          echo "Build Successful."
        else
          echo "Build Failed!"
          exit 1
        fi
        npm run start
